### ISSUE TITLE
Featured image

### ISSUE THREAD

**Issue by ugurcandede** [oukan/oukan-wordpress-ionic#1]
@oukan Please add featured images on single post.

For example:
![single post](https://cloud.githubusercontent.com/assets/7129112/8839899/3082dc52-30e3-11e5-89da-bd92c5b541dc.png)

**Comment by ugurcandede** [comment]
This image Reactor API was used.
I don't know how to add featured images with wp-json api . Please say how to add.

**Comment by oukan** [comment]
1. In Wordpress admin,  when you are add a post, you must set a featured image.
2. just like http://www.oukan.net/wp-json/posts/1546 , you can find [ "source": "http://www.oukan.net/wp-content/uploads/2014/06/key.jpg", ], this is the featured image web address.
3. add this featured image web address in you code.

**Comment by oukan** [comment]
you can see https://github.com/oukan/wordpress-restful-ionic/commit/044689ad5e1b2283cf33b440c1c41d7c568c4d8c

**Comment by ugurcandede** [comment]
Thank @oukan. I add the code you're given.It works great.
But there will be one more question.

<img class = "featured-image" ng-src = "{{p.featured_image.attachment_meta.sizes.thumbnail.url}}">

this code does not work when I add a single post. How can I fix this?

**Comment by ugurcandede** [comment]
Another question
I give HTML Character Code Error

For example;
"Sony Xperia Sahipleri Android M<b>’</b>yi Kullanabilir" instead "Sony Xperia Sahipleri Android M<b>&#8217</b>yi Kullanabilir"

<img src="http://cdn.teknotik.org/ionic-app/Ekran%20G%C3%B6r%C3%BCnt%C3%BCs%C3%BC%202015-07-27%2017.45.46.png">

Example link: http://www.teknotik.org/haberler/sony-xperia-sahipleri-android-myi-kullanabilir.html

**Comment by oukan** [comment]
in Ionic app 'index.html' charset must set be `<meta charset="utf-8">`

**Comment by ugurcandede** [comment]
Already set to UTF-8.
